docs(fix): Update API arguments
dgraph-io/cloud-docs pull request #47
Opened 2021-04-23 14:46 UTC by bucanero

2021-04-23 15:40 UTC, verneleem requested changes

2021-04-23 15:40 UTC, verneleem commented on content/cloud-api/backend.md
>    * `name`: name of the deployment
We don't do the type dotted notation here, but we do it on the same page below in the updateDeploymentInput. We need consistency one way or the other

2021-04-23 15:40 UTC, verneleem commented on content/cloud-api/schema.md
> +  updateGQLSchema(input: { set: { schema: $schema } }) {
This also needs changed on line 100 above.

2021-04-23 15:40 UTC, verneleem commented on content/cloud-api/lambda.md
> +query GetLambdaLogs($lambdaLogsInput: LambdaLogsInput!) {
similar changes needs done on lines 138-147 and 204-213

2021-04-28 14:47 UTC, bucanero commented on content/cloud-api/lambda.md
> +query GetLambdaLogs($lambdaLogsInput: LambdaLogsInput!) {
fixed

2021-04-28 14:47 UTC, bucanero commented on content/cloud-api/schema.md
> +  updateGQLSchema(input: { set: { schema: $schema } }) {
fixed

2021-04-28 14:47 UTC, bucanero commented on content/cloud-api/backend.md
>    * `name`: name of the deployment
fixed

2021-04-28 14:54 UTC, merged